#
# * Copyright © Michael O'Rourke
# *
# * _config.yml
# * Localized configuration file. Config values should always be defined in _config.yml. Do
# * not edit existing config values. Only add new application-scoped config values.
#

# ==============================
# Project
# ==============================

github:
  title:        Product Charter
  tagline:      Practical concepts to help improve how you make products.
  owner:        "Michael O'Rourke"
  license:      Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License
  user:
    name:       caleorourke
    repo:       product-charter

# ==============================
# Social
# ==============================

website:        http://medium.com/@caleorourke
twitter:
  handle:       CaleORourke
  hashtags:     "products,lean,agile"
  text:         Learn practical concepts to improve how you make products
keywords:       "agile,charter,command-control-execute,content,design,essentials,framework,kaizen,kanban,lean,lifecycle,methodology,practical,pragmatic,pragmatic marketing,product,productization,product management,product teams,project management,responsibilities,roles,scaffolding,scrum,strategy,tactics,vision,zen"

# ==============================
# Markdown
# ==============================

markdown:       redcarpet
redcarpet:
  extensions:   ["autolink",
                 "fenced_code_blocks",
                 "highlight",
                 "lax_spacing",
                 "smart",
                 "strikethrough",
                 "superscript",
                 "tables",
                 "underline",
                 "with_toc_data"]

# ==============================
# Server
# ==============================

baseurl:        /product-charter
permalink:      pretty
exclude:        [".csscomb.json",
                 ".gitignore",
                 "Gruntfile.js",
                 "less",
                 "node_modules",
                 "package.json",
                 "pages/drafts",
                 "README.md",
                 "vendors"]
gems:
  - jekyll-sitemap
